'use strict';

module.exports = {
  extends: ['stylelint-config-prettier'],
  plugins: ['stylelint-mirego', 'stylelint-order'],
  rules: {
    'at-rule-no-unknown': [
      true,
      {ignoreAtRules: ['mixin', 'content', 'include']},
    ],
    'at-rule-no-vendor-prefix': true,
    'block-no-empty': true,
    'color-hex-length': 'short',
    'color-no-invalid-hex': true,
    'comment-empty-line-before': 'always',
    'comment-whitespace-inside': 'always',
    'declaration-block-no-shorthand-property-overrides': true,
    'declaration-block-single-line-max-declarations': 1,
    'declaration-property-value-disallowed-list': {'/^border/': ['none']},
    'function-calc-no-unspaced-operator': true,
    'function-linear-gradient-no-nonstandard-direction': true,
    'function-url-quotes': 'always',
    'function-whitespace-after': 'always',
    'length-zero-no-unit': true,
    'media-feature-name-no-unknown': true,
    'media-feature-name-no-vendor-prefix': true,
    'media-feature-range-operator-space-after': 'always',
    'media-feature-range-operator-space-before': 'always',
    'mirego/box-shadow-optional-values': 2,
    'mirego/prefer-sass-rgba-function': 2,
    'mirego/single-decimal-line-height': 2,
    'no-unknown-animations': true,
    'order/properties-order': [
      [
        'box-sizing',
        'display',
        'content',
        'position',
        'z-index',
        'top',
        'right',
        'bottom',
        'left',
        'opacity',
        'transform',
        'transform-origin',
        'transform-style',
        'flex',
        'order',
        'align-self',
        'flex-direction',
        'justify-content',
        'align-items',
        'flex-wrap',
        'align-content',
        'flex-flow',
        'overflow',
        'overflow-x',
        'overflow-y',
        'width',
        'min-width',
        'max-width',
        'height',
        'min-height',
        'max-height',
        'padding',
        'padding-top',
        'padding-right',
        'padding-bottom',
        'padding-left',
        'border',
        'border-top',
        'border-right',
        'border-bottom',
        'border-left',
        'border-color',
        'border-style',
        'border-width',
        'border-radius',
        'margin',
        'margin-top',
        'margin-right',
        'margin-bottom',
        'margin-left',
        'list-style',
        'list-style-image',
        'list-style-position',
        'list-style-type',
        'background',
        'background-clip',
        'background-color',
        'background-image',
        'background-origin',
        'background-position',
        'background-repeat',
        'background-size',
        'fill',
        'box-shadow',
        'outline',
        'text-align',
        'text-decoration',
        'text-overflow',
        'text-shadow',
        'text-transform',
        'white-space',
        'font',
        'font-family',
        'font-size',
        'font-style',
        'font-weight',
        'line-height',
        'letter-spacing',
        'color',
        'animation',
        'animation-delay',
        'animation-direction',
        'animation-duration',
        'animation-name',
        'transition',
        'transition-delay',
        'transition-duration',
        'transition-property',
      ],
      {unspecified: 'bottomAlphabetical'},
    ],
    'property-no-unknown': [true, {checkPrefixed: true}],
    'property-no-vendor-prefix': true,
    'selector-no-vendor-prefix': true,
    'selector-pseudo-class-no-unknown': true,
    'selector-pseudo-element-colon-notation': 'double',
    'selector-pseudo-element-no-unknown': true,
    'selector-type-no-unknown': true,
    'shorthand-property-no-redundant-values': true,
    'unit-no-unknown': true,
    'value-no-vendor-prefix': true,
  },
};
